# Generated by Django 3.2.9 on 2021-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='', width_field=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kilograms', 'kilogram'), ('pounds', 'pound'), ('grams', 'gram'), ('ounce', 'ounce'), ('counts', 'count')], default='grams', max_length=10),
        ),
    ]
