# Generated by Django 3.2.9 on 2021-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('oz', 'ounce'), ('ea', 'each'), ('lb', 'pounds')], default='g', max_length=2),
        ),
    ]
