# Generated by Django 3.2.9 on 2021-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('lb', 'pounds'), ('ea', 'each'), ('kg', 'kilograms'), ('g', 'grams'), ('oz', 'ounce')], default='g', max_length=2),
        ),
    ]
