# Generated by Django 3.2.9 on 2021-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211207_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('grams', 'gram'), ('kilograms', 'kilogram'), ('ounce', 'ounce'), ('pounds', 'pound'), ('counts', 'count')], default='grams', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
