# Generated by Django 3.2.9 on 2021-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('pounds', 'pound'), ('counts', 'count'), ('ounce', 'ounce'), ('kilograms', 'kilogram'), ('grams', 'gram')], default='grams', max_length=10),
        ),
    ]
