# Generated by Django 3.2.9 on 2021-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211207_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('grams', 'gram'), ('kilograms', 'kilogram'), ('pounds', 'pound'), ('counts', 'count'), ('ounce', 'ounce')], default='grams', max_length=10),
        ),
    ]
