# Generated by Django 3.2.9 on 2021-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('pounds', 'pound'), ('counts', 'count'), ('ounce', 'ounce'), ('kilograms', 'kilogram'), ('grams', 'gram')], default='grams', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
