# Generated by Django 3.2.9 on 2021-12-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20211207_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('counts', 'count'), ('grams', 'gram'), ('pounds', 'pound'), ('kilograms', 'kilogram'), ('ounce', 'ounce')], default='grams', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menuitem_images/'),
        ),
    ]
