# Generated by Django 3.2.9 on 2021-12-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20211207_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('pounds', 'pound'), ('grams', 'gram'), ('kilograms', 'kilogram'), ('counts', 'count'), ('ounce', 'ounce')], default='grams', max_length=10),
        ),
    ]
